// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alterapplicationusertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterapplicationusertable));
        
        string IMigrationMetadata.Id
        {
            get { return "202110071952509_alter-application-user-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
