// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addtrainertraineeprofiletables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtrainertraineeprofiletables));
        
        string IMigrationMetadata.Id
        {
            get { return "202110140619213_add-trainer-trainee-profile-tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
